// ===== NZ Services Directory — Data =====

const REGIONS = [
    { id: 'northland', name: 'Northland', city: 'Whangārei', count: 142 },
    { id: 'auckland', name: 'Auckland', city: 'Auckland', count: 687 },
    { id: 'waikato', name: 'Waikato', city: 'Hamilton', count: 234 },
    { id: 'bay-of-plenty', name: 'Bay of Plenty', city: 'Tauranga', count: 198 },
    { id: 'gisborne', name: 'Gisborne', city: 'Gisborne', count: 56 },
    { id: 'hawkes-bay', name: "Hawke's Bay", city: 'Napier', count: 124 },
    { id: 'taranaki', name: 'Taranaki', city: 'New Plymouth', count: 89 },
    { id: 'manawatu-whanganui', name: 'Manawatū-Whanganui', city: 'Palmerston North', count: 112 },
    { id: 'wellington', name: 'Wellington', city: 'Wellington', count: 378 },
    { id: 'nelson-tasman', name: 'Nelson-Tasman', city: 'Nelson', count: 87 },
    { id: 'marlborough', name: 'Marlborough', city: 'Blenheim', count: 54 },
    { id: 'west-coast', name: 'West Coast', city: 'Greymouth', count: 38 },
    { id: 'canterbury', name: 'Canterbury', city: 'Christchurch', count: 412 },
    { id: 'otago', name: 'Otago', city: 'Dunedin', count: 198 },
    { id: 'southland', name: 'Southland', city: 'Invercargill', count: 76 },
];

const CATEGORIES = [
    { id: 'plumbing', name: 'Plumbing', icon: '🔧', color: '#3B82F6', bg: '#EFF6FF', count: 312 },
    { id: 'electrical', name: 'Electrical', icon: '⚡', color: '#F59E0B', bg: '#FFFBEB', count: 287 },
    { id: 'building', name: 'Building & Construction', icon: '🏗️', color: '#EF4444', bg: '#FEF2F2', count: 456 },
    { id: 'cleaning', name: 'Cleaning', icon: '✨', color: '#06B6D4', bg: '#ECFEFF', count: 198 },
    { id: 'landscaping', name: 'Landscaping', icon: '🌿', color: '#22C55E', bg: '#F0FDF4', count: 167 },
    { id: 'painting', name: 'Painting & Decorating', icon: '🎨', color: '#A855F7', bg: '#FAF5FF', count: 143 },
    { id: 'roofing', name: 'Roofing', icon: '🏠', color: '#78716C', bg: '#FAFAF9', count: 98 },
    { id: 'it-tech', name: 'IT & Technology', icon: '💻', color: '#6366F1', bg: '#EEF2FF', count: 234 },
    { id: 'accounting', name: 'Accounting & Finance', icon: '📊', color: '#0D9488', bg: '#F0FDFA', count: 189 },
    { id: 'legal', name: 'Legal Services', icon: '⚖️', color: '#1E293B', bg: '#F8FAFC', count: 156 },
    { id: 'health', name: 'Health & Wellness', icon: '🏥', color: '#EC4899', bg: '#FDF2F8', count: 278 },
    { id: 'automotive', name: 'Automotive', icon: '🚗', color: '#64748B', bg: '#F1F5F9', count: 167 },
    { id: 'photography', name: 'Photography', icon: '📸', color: '#D946EF', bg: '#FDF4FF', count: 123 },
    { id: 'events', name: 'Event Planning', icon: '🎉', color: '#F97316', bg: '#FFF7ED', count: 89 },
    { id: 'real-estate', name: 'Real Estate', icon: '🏡', color: '#14B8A6', bg: '#F0FDFA', count: 198 },
    { id: 'education', name: 'Education & Tutoring', icon: '📚', color: '#8B5CF6', bg: '#F5F3FF', count: 145 },
    { id: 'locksmith', name: 'Locksmith', icon: '🔑', color: '#CA8A04', bg: '#FEFCE8', count: 67 },
    { id: 'pest-control', name: 'Pest Control', icon: '🐛', color: '#65A30D', bg: '#F7FEE7', count: 78 },
    { id: 'moving', name: 'Moving & Removals', icon: '📦', color: '#0284C7', bg: '#F0F9FF', count: 112 },
    { id: 'security', name: 'Security Services', icon: '🔒', color: '#334155', bg: '#F8FAFC', count: 86 },
];

const AVATAR_COLORS = [
    '#3B82F6', '#EF4444', '#F59E0B', '#22C55E', '#A855F7',
    '#EC4899', '#06B6D4', '#6366F1', '#14B8A6', '#F97316',
    '#0D9488', '#8B5CF6', '#D946EF', '#0284C7', '#CA8A04',
];

// Sample NZ service provider data — independent and agency
const LISTINGS = [
    {
        id: 1,
        name: 'Mike Thompson Plumbing',
        type: 'independent',
        category: 'plumbing',
        region: 'auckland',
        city: 'Auckland CBD',
        phone: '021 345 6789',
        email: 'mike@thompsonplumbing.co.nz',
        website: 'thompsonplumbing.co.nz',
        rating: 4.9,
        reviews: 127,
        verified: true,
        featured: true,
        description: 'Master plumber with 20+ years experience serving Auckland. Specialising in residential repairs, hot water systems, and bathroom renovations. Prompt, reliable, and competitively priced.',
        services: ['Emergency Repairs', 'Hot Water Systems', 'Bathroom Renovation', 'Drain Clearing', 'Gas Fitting'],
    },
    {
        id: 2,
        name: 'Kiwi Electrical Solutions',
        type: 'agency',
        category: 'electrical',
        region: 'wellington',
        city: 'Lower Hutt',
        phone: '04 567 8901',
        email: 'info@kiwielectrical.co.nz',
        website: 'kiwielectrical.co.nz',
        rating: 4.8,
        reviews: 203,
        verified: true,
        featured: true,
        description: 'Wellington\'s trusted electrical agency with a team of 15 certified electricians. Commercial and residential services including new builds, rewiring, and smart home installations.',
        services: ['New Builds', 'Rewiring', 'Smart Home', 'Commercial Fit-out', 'Safety Inspections', 'EV Chargers'],
    },
    {
        id: 3,
        name: 'Sarah Chen Photography',
        type: 'independent',
        category: 'photography',
        region: 'otago',
        city: 'Queenstown',
        phone: '027 890 1234',
        email: 'hello@sarahchen.co.nz',
        website: 'sarahchenphotography.co.nz',
        rating: 5.0,
        reviews: 89,
        verified: true,
        featured: true,
        description: 'Award-winning photographer based in Queenstown. Specialising in weddings, elopements, and corporate events with a natural, documentary style. Alpine and lakeside shoots a specialty.',
        services: ['Weddings', 'Elopements', 'Corporate Events', 'Portraits', 'Commercial'],
    },
    {
        id: 4,
        name: 'Canterbury Build Group',
        type: 'agency',
        category: 'building',
        region: 'canterbury',
        city: 'Christchurch',
        phone: '03 345 6789',
        email: 'projects@canterburybuild.co.nz',
        website: 'canterburybuild.co.nz',
        rating: 4.7,
        reviews: 312,
        verified: true,
        featured: true,
        description: 'Full-service construction company rebuilding Canterbury since 2011. New homes, commercial buildings, and earthquake strengthening. Licensed Building Practitioners on staff.',
        services: ['New Homes', 'Commercial', 'Earthquake Strengthening', 'Renovations', 'Project Management'],
    },
    {
        id: 5,
        name: 'GreenScape Landscapes',
        type: 'agency',
        category: 'landscaping',
        region: 'auckland',
        city: 'North Shore',
        phone: '09 456 7890',
        email: 'design@greenscapenz.co.nz',
        website: 'greenscapenz.co.nz',
        rating: 4.8,
        reviews: 156,
        verified: true,
        featured: false,
        description: 'Award-winning landscape design and construction on Auckland\'s North Shore. Creating beautiful outdoor living spaces, gardens, and sustainable landscaping solutions.',
        services: ['Garden Design', 'Retaining Walls', 'Paving', 'Planting', 'Irrigation', 'Outdoor Living'],
    },
    {
        id: 6,
        name: 'Tara Williams — Barrister & Solicitor',
        type: 'independent',
        category: 'legal',
        region: 'wellington',
        city: 'Wellington CBD',
        phone: '04 234 5678',
        email: 'tara@williamslegal.co.nz',
        website: 'williamslegal.co.nz',
        rating: 4.9,
        reviews: 67,
        verified: true,
        featured: false,
        description: 'Experienced family and employment lawyer practicing in Wellington. Providing clear, practical legal advice with a focus on resolution. Free initial consultation available.',
        services: ['Family Law', 'Employment Law', 'Mediation', 'Property Law', 'Wills & Trusts'],
    },
    {
        id: 7,
        name: 'TechForward IT Services',
        type: 'agency',
        category: 'it-tech',
        region: 'auckland',
        city: 'Parnell',
        phone: '09 876 5432',
        email: 'support@techforward.co.nz',
        website: 'techforward.co.nz',
        rating: 4.6,
        reviews: 234,
        verified: true,
        featured: true,
        description: 'Auckland\'s leading managed IT services provider. Supporting SMEs with network management, cybersecurity, cloud migration, and helpdesk support. 24/7 monitoring available.',
        services: ['Managed IT', 'Cybersecurity', 'Cloud Services', 'Helpdesk', 'Network Setup', 'Data Backup'],
    },
    {
        id: 8,
        name: 'Clean & Gleam NZ',
        type: 'agency',
        category: 'cleaning',
        region: 'waikato',
        city: 'Hamilton',
        phone: '07 345 6789',
        email: 'book@cleanandgleam.co.nz',
        website: 'cleanandgleam.co.nz',
        rating: 4.7,
        reviews: 189,
        verified: true,
        featured: false,
        description: 'Professional cleaning services across the Waikato region. Residential, commercial, and end-of-tenancy cleaning. Eco-friendly products used. Fully insured team.',
        services: ['House Cleaning', 'Office Cleaning', 'End of Tenancy', 'Carpet Cleaning', 'Window Cleaning'],
    },
    {
        id: 9,
        name: 'Dave\'s Roofing Northland',
        type: 'independent',
        category: 'roofing',
        region: 'northland',
        city: 'Whangārei',
        phone: '021 567 8901',
        email: 'dave@davesroofing.co.nz',
        website: 'davesroofing.co.nz',
        rating: 4.8,
        reviews: 76,
        verified: true,
        featured: false,
        description: 'Northland\'s trusted roofer. Re-roofing, repairs, spouting, and fascia. Working with Colorsteel, tiles, and butynol. Free quotes and honest advice — no job too small.',
        services: ['Re-roofing', 'Repairs', 'Spouting', 'Fascia', 'Colorsteel', 'Tile Roofing'],
    },
    {
        id: 10,
        name: 'Aroha Accounting',
        type: 'agency',
        category: 'accounting',
        region: 'bay-of-plenty',
        city: 'Tauranga',
        phone: '07 234 5678',
        email: 'team@arohaaccounting.co.nz',
        website: 'arohaaccounting.co.nz',
        rating: 4.9,
        reviews: 145,
        verified: true,
        featured: true,
        description: 'Chartered accountants and business advisors in Tauranga. Tax returns, GST, payroll, and business planning. We make numbers simple for small business owners and contractors.',
        services: ['Tax Returns', 'GST', 'Payroll', 'Business Planning', 'Company Setup', 'Xero Advisory'],
    },
    {
        id: 11,
        name: 'Peak Fitness Coaching',
        type: 'independent',
        category: 'health',
        region: 'canterbury',
        city: 'Christchurch',
        phone: '027 123 4567',
        email: 'coach@peakfitness.co.nz',
        website: 'peakfitness.co.nz',
        rating: 4.9,
        reviews: 98,
        verified: true,
        featured: false,
        description: 'Personal training and wellness coaching in Christchurch. Certified in strength training, nutrition, and rehabilitation. In-home and online sessions available for all fitness levels.',
        services: ['Personal Training', 'Nutrition Plans', 'Rehabilitation', 'Group Fitness', 'Online Coaching'],
    },
    {
        id: 12,
        name: 'Precision Painters',
        type: 'agency',
        category: 'painting',
        region: 'auckland',
        city: 'East Auckland',
        phone: '09 567 8901',
        email: 'quotes@precisionpainters.co.nz',
        website: 'precisionpainters.co.nz',
        rating: 4.6,
        reviews: 167,
        verified: true,
        featured: false,
        description: 'Professional painting and decorating services across Auckland. Interior and exterior, residential and commercial. Dulux accredited, fully insured, and quality guaranteed.',
        services: ['Interior Painting', 'Exterior Painting', 'Wallpapering', 'Roof Painting', 'Commercial'],
    },
    {
        id: 13,
        name: 'Taranaki Auto Specialists',
        type: 'agency',
        category: 'automotive',
        region: 'taranaki',
        city: 'New Plymouth',
        phone: '06 789 0123',
        email: 'service@taranakauto.co.nz',
        website: 'taranakauto.co.nz',
        rating: 4.7,
        reviews: 112,
        verified: true,
        featured: false,
        description: 'Full-service automotive workshop in New Plymouth. WOF, servicing, repairs, and performance upgrades. Experienced with all makes and models. European car specialists.',
        services: ['WOF Inspections', 'Full Servicing', 'Repairs', 'European Cars', 'Performance', 'Diagnostics'],
    },
    {
        id: 14,
        name: 'Celebrate Events Co.',
        type: 'agency',
        category: 'events',
        region: 'wellington',
        city: 'Wellington',
        phone: '04 890 1234',
        email: 'hello@celebrateco.co.nz',
        website: 'celebrateco.co.nz',
        rating: 4.8,
        reviews: 78,
        verified: true,
        featured: false,
        description: 'Wellington\'s premier event planning company. Weddings, corporate events, private parties, and festivals. Full-service planning from concept to execution with creative flair.',
        services: ['Wedding Planning', 'Corporate Events', 'Private Parties', 'Festival Management', 'Styling'],
    },
    {
        id: 15,
        name: 'Ben Taylor — Locksmith',
        type: 'independent',
        category: 'locksmith',
        region: 'canterbury',
        city: 'Christchurch',
        phone: '027 456 7890',
        email: 'ben@bentaylorlocksmith.co.nz',
        website: 'bentaylorlocksmith.co.nz',
        rating: 4.8,
        reviews: 54,
        verified: true,
        featured: false,
        description: 'Emergency and scheduled locksmith services across Canterbury. Residential, commercial, and automotive. 24/7 availability. Fast response times and upfront pricing.',
        services: ['Emergency Lockout', 'Lock Changes', 'Key Cutting', 'Automotive', 'Security Systems', 'Safes'],
    },
    {
        id: 16,
        name: 'Hauraki Pest Solutions',
        type: 'independent',
        category: 'pest-control',
        region: 'waikato',
        city: 'Thames',
        phone: '021 678 9012',
        email: 'help@haurakipest.co.nz',
        website: 'haurakipest.co.nz',
        rating: 4.5,
        reviews: 43,
        verified: true,
        featured: false,
        description: 'Pest control expert covering the Waikato and Coromandel. Rodents, possums, wasps, spiders, and commercial pest management. Environmentally responsible treatments.',
        services: ['Rodent Control', 'Possum Removal', 'Wasp Nests', 'Spider Treatment', 'Commercial Pest Management'],
    },
    {
        id: 17,
        name: 'Southern Move Logistics',
        type: 'agency',
        category: 'moving',
        region: 'otago',
        city: 'Dunedin',
        phone: '03 456 7890',
        email: 'book@southernmove.co.nz',
        website: 'southernmove.co.nz',
        rating: 4.6,
        reviews: 89,
        verified: true,
        featured: false,
        description: 'Professional moving and removals service based in Dunedin. Local moves, long-distance, and storage solutions. Packing services available. Careful, insured, and punctual.',
        services: ['Local Moves', 'Long Distance', 'Packing', 'Storage', 'Office Relocation', 'Piano Moving'],
    },
    {
        id: 18,
        name: 'Hawke\'s Bay Real Estate Group',
        type: 'agency',
        category: 'real-estate',
        region: 'hawkes-bay',
        city: 'Napier',
        phone: '06 345 6789',
        email: 'sales@hbrealestate.co.nz',
        website: 'hbrealestate.co.nz',
        rating: 4.7,
        reviews: 178,
        verified: true,
        featured: true,
        description: 'Leading real estate agency in Hawke\'s Bay. Residential and commercial sales, property management, and valuations. Local knowledge you can trust — selling homes since 1995.',
        services: ['Residential Sales', 'Commercial Sales', 'Property Management', 'Valuations', 'Auctions'],
    },
    {
        id: 19,
        name: 'NZ Security Professionals',
        type: 'agency',
        category: 'security',
        region: 'auckland',
        city: 'Manukau',
        phone: '09 234 5678',
        email: 'operations@nzsecuritypro.co.nz',
        website: 'nzsecuritypro.co.nz',
        rating: 4.5,
        reviews: 123,
        verified: true,
        featured: false,
        description: 'Licensed security company providing guard services, event security, mobile patrols, and CCTV installation across Auckland. Professional, reliable, and MSD certified staff.',
        services: ['Guard Services', 'Event Security', 'Mobile Patrols', 'CCTV Installation', 'Access Control'],
    },
    {
        id: 20,
        name: 'Maths Mastery Tutoring',
        type: 'independent',
        category: 'education',
        region: 'wellington',
        city: 'Porirua',
        phone: '021 012 3456',
        email: 'learn@mathsmastery.co.nz',
        website: 'mathsmastery.co.nz',
        rating: 4.9,
        reviews: 67,
        verified: true,
        featured: false,
        description: 'Expert maths tutor helping students from Year 7 through to university level. NCEA and Cambridge curriculum specialist. One-on-one and small group sessions in Porirua and online.',
        services: ['NCEA Maths', 'Cambridge Maths', 'University Prep', 'Small Groups', 'Online Tutoring'],
    },
    {
        id: 21,
        name: 'Nelson Sparks Electrical',
        type: 'independent',
        category: 'electrical',
        region: 'nelson-tasman',
        city: 'Nelson',
        phone: '027 345 6789',
        email: 'sparks@nelsonsparks.co.nz',
        website: 'nelsonsparks.co.nz',
        rating: 4.7,
        reviews: 56,
        verified: true,
        featured: false,
        description: 'Registered electrician serving Nelson and Tasman. New installations, maintenance, LED upgrades, and solar panel systems. Prompt, tidy, and always on time.',
        services: ['New Installations', 'LED Upgrades', 'Solar Panels', 'Heat Pumps', 'Maintenance'],
    },
    {
        id: 22,
        name: 'Waikato Drain Masters',
        type: 'independent',
        category: 'plumbing',
        region: 'waikato',
        city: 'Hamilton',
        phone: '021 234 5678',
        email: 'drains@waikatodrains.co.nz',
        website: 'waikatodrains.co.nz',
        rating: 4.6,
        reviews: 89,
        verified: true,
        featured: false,
        description: 'Drain unblocking and plumbing specialist in Hamilton and surrounding Waikato. CCTV pipe inspections, water blasting, and septic tank services. Emergency callouts available 24/7.',
        services: ['Drain Unblocking', 'CCTV Inspections', 'Septic Tanks', 'Water Blasting', 'Emergency Plumbing'],
    },
    {
        id: 23,
        name: 'Southland IT Hub',
        type: 'agency',
        category: 'it-tech',
        region: 'southland',
        city: 'Invercargill',
        phone: '03 567 8901',
        email: 'hello@southlandithub.co.nz',
        website: 'southlandithub.co.nz',
        rating: 4.4,
        reviews: 34,
        verified: true,
        featured: false,
        description: 'IT support and solutions for businesses in Southland. Computer repairs, network installations, website development, and managed services. Local team, personal approach.',
        services: ['Computer Repairs', 'Networking', 'Web Development', 'Managed Services', 'Cloud Setup'],
    },
    {
        id: 24,
        name: 'Bay Builders Co.',
        type: 'agency',
        category: 'building',
        region: 'bay-of-plenty',
        city: 'Mount Maunganui',
        phone: '07 890 1234',
        email: 'build@baybuilders.co.nz',
        website: 'baybuilders.co.nz',
        rating: 4.8,
        reviews: 145,
        verified: true,
        featured: false,
        description: 'Licensed building company in Mount Maunganui specialising in coastal homes, renovations, and light commercial projects. Master Builder member with a 10-year guarantee.',
        services: ['New Homes', 'Renovations', 'Decks & Outdoor', 'Light Commercial', 'Project Management'],
    },
    {
        id: 25,
        name: 'West Coast Wellness',
        type: 'independent',
        category: 'health',
        region: 'west-coast',
        city: 'Greymouth',
        phone: '027 567 8901',
        email: 'wellness@westcoastwellness.co.nz',
        website: 'westcoastwellness.co.nz',
        rating: 4.6,
        reviews: 28,
        verified: true,
        featured: false,
        description: 'Holistic health and wellness practitioner on the West Coast. Massage therapy, naturopathy, and yoga instruction. Creating balance and wellbeing in the heart of the Coast.',
        services: ['Massage Therapy', 'Naturopathy', 'Yoga Classes', 'Mindfulness', 'Nutrition Advice'],
    },
    {
        id: 26,
        name: 'Marlborough Vintners Real Estate',
        type: 'agency',
        category: 'real-estate',
        region: 'marlborough',
        city: 'Blenheim',
        phone: '03 678 9012',
        email: 'sales@mvrealestate.co.nz',
        website: 'mvrealestate.co.nz',
        rating: 4.7,
        reviews: 67,
        verified: true,
        featured: false,
        description: 'Boutique real estate agency specialising in Marlborough lifestyle and vineyard properties. Residential sales, rural properties, and vineyards. Friendly local team since 2003.',
        services: ['Residential Sales', 'Lifestyle Properties', 'Vineyard Sales', 'Rural Properties', 'Rentals'],
    },
    {
        id: 27,
        name: 'Gisborne Clean Team',
        type: 'agency',
        category: 'cleaning',
        region: 'gisborne',
        city: 'Gisborne',
        phone: '06 456 7890',
        email: 'book@gisborneclean.co.nz',
        website: 'gisborneclean.co.nz',
        rating: 4.5,
        reviews: 34,
        verified: true,
        featured: false,
        description: 'First light, first clean! Gisborne\'s professional cleaning company. Houses, offices, and post-construction clean-ups. Reliable local team using quality products.',
        services: ['House Cleaning', 'Office Cleaning', 'Post-Construction', 'Window Cleaning', 'Carpet Cleaning'],
    },
    {
        id: 28,
        name: 'Manawatū Painting Pros',
        type: 'independent',
        category: 'painting',
        region: 'manawatu-whanganui',
        city: 'Palmerston North',
        phone: '021 789 0123',
        email: 'quotes@manawatupainting.co.nz',
        website: 'manawatupainting.co.nz',
        rating: 4.7,
        reviews: 56,
        verified: true,
        featured: false,
        description: 'Quality painter and decorator serving Palmerston North and Manawatū. Interior, exterior, and commercial painting. Colour consultation available. Tidy, efficient, and reliable.',
        services: ['Interior Painting', 'Exterior Painting', 'Commercial', 'Colour Consultation', 'Spray Painting'],
    },
    {
        id: 29,
        name: 'Auckland Auto Clinic',
        type: 'independent',
        category: 'automotive',
        region: 'auckland',
        city: 'Grey Lynn',
        phone: '09 789 0123',
        email: 'service@aucklandautoclinic.co.nz',
        website: 'aucklandautoclinic.co.nz',
        rating: 4.8,
        reviews: 198,
        verified: true,
        featured: true,
        description: 'Independent mechanic in Grey Lynn specialising in Japanese and Korean vehicles. Honest assessments, fair prices, and quality workmanship. WOF testing station on site.',
        services: ['WOF Testing', 'Full Service', 'Repairs', 'Japanese Cars', 'Korean Cars', 'Diagnostics'],
    },
    {
        id: 30,
        name: 'StudySmart Tutoring',
        type: 'agency',
        category: 'education',
        region: 'canterbury',
        city: 'Christchurch',
        phone: '03 890 1234',
        email: 'enrol@studysmart.co.nz',
        website: 'studysmart.co.nz',
        rating: 4.8,
        reviews: 112,
        verified: true,
        featured: false,
        description: 'Canterbury\'s leading tutoring centre. All subjects, all levels — primary through to university. Qualified teachers, proven results, and flexible scheduling. First session free.',
        services: ['Primary Tutoring', 'High School', 'NCEA Prep', 'University Support', 'English Language', 'Sciences'],
    },
    {
        id: 31,
        name: 'Apex Security Otago',
        type: 'agency',
        category: 'security',
        region: 'otago',
        city: 'Queenstown',
        phone: '03 234 5678',
        email: 'ops@apexsecurityotago.co.nz',
        website: 'apexsecurityotago.co.nz',
        rating: 4.6,
        reviews: 45,
        verified: true,
        featured: false,
        description: 'Security services for Queenstown, Wanaka, and wider Otago. Event security, hospitality security, alarm monitoring, and patrol services. Trusted by major venues and events.',
        services: ['Event Security', 'Hospitality', 'Alarm Monitoring', 'Patrols', 'VIP Protection'],
    },
    {
        id: 32,
        name: 'Coastal Landscapes BOP',
        type: 'independent',
        category: 'landscaping',
        region: 'bay-of-plenty',
        city: 'Papamoa',
        phone: '027 678 9012',
        email: 'design@coastallandscapes.co.nz',
        website: 'coastallandscapes.co.nz',
        rating: 4.9,
        reviews: 78,
        verified: true,
        featured: false,
        description: 'Creative landscaper crafting beautiful coastal gardens in Papamoa and Bay of Plenty. Native planting, hardscaping, and outdoor living spaces. Design through to completion.',
        services: ['Native Gardens', 'Hardscaping', 'Outdoor Living', 'Garden Maintenance', 'Irrigation'],
    },
    {
        id: 33,
        name: 'Number Crunchers Accounting',
        type: 'independent',
        category: 'accounting',
        region: 'auckland',
        city: 'Newmarket',
        phone: '09 012 3456',
        email: 'hello@numbercrunchers.co.nz',
        website: 'numbercrunchers.co.nz',
        rating: 4.8,
        reviews: 134,
        verified: true,
        featured: false,
        description: 'Modern chartered accountant in Newmarket helping businesses grow. Xero certified, cloud-based workflow, proactive advice. Specialising in startups, freelancers, and SMEs.',
        services: ['Tax Returns', 'Xero Setup', 'Business Advisory', 'Startup Accounting', 'Payroll', 'GST Filing'],
    },
    {
        id: 34,
        name: 'Rapid Response Plumbing',
        type: 'agency',
        category: 'plumbing',
        region: 'canterbury',
        city: 'Riccarton',
        phone: '03 012 3456',
        email: 'urgent@rapidplumbing.co.nz',
        website: 'rapidplumbing.co.nz',
        rating: 4.5,
        reviews: 167,
        verified: true,
        featured: false,
        description: 'Canterbury\'s 24/7 emergency plumbing service. Burst pipes, blocked drains, hot water failures — we come to you fast. Upfront pricing with no hidden fees.',
        services: ['Emergency Plumbing', 'Burst Pipes', 'Blocked Drains', 'Hot Water', 'Leak Detection'],
    },
    {
        id: 35,
        name: 'Whanganui Web Design',
        type: 'independent',
        category: 'it-tech',
        region: 'manawatu-whanganui',
        city: 'Whanganui',
        phone: '021 890 1234',
        email: 'create@whanganuiweb.co.nz',
        website: 'whanganuiweb.co.nz',
        rating: 4.7,
        reviews: 45,
        verified: true,
        featured: false,
        description: 'Freelance web designer and developer in Whanganui. WordPress, Shopify, and custom websites. Helping local businesses get online with professional, affordable websites.',
        services: ['WordPress', 'Shopify', 'Custom Websites', 'SEO', 'Hosting', 'Maintenance'],
    },
    {
        id: 36,
        name: 'Top Notch Builders Northland',
        type: 'agency',
        category: 'building',
        region: 'northland',
        city: 'Kerikeri',
        phone: '09 123 4567',
        email: 'build@topnotchnorthland.co.nz',
        website: 'topnotchnorthland.co.nz',
        rating: 4.6,
        reviews: 67,
        verified: true,
        featured: false,
        description: 'Building excellence in the Far North. New homes, renovations, and bach builds. Licensed Building Practitioners specialising in timber and sustainable construction.',
        services: ['New Homes', 'Renovations', 'Bach Builds', 'Sustainable Building', 'Timber Construction'],
    },
    {
        id: 37,
        name: 'Hamilton Family Law',
        type: 'agency',
        category: 'legal',
        region: 'waikato',
        city: 'Hamilton',
        phone: '07 012 3456',
        email: 'enquiry@hamiltonfamilylaw.co.nz',
        website: 'hamiltonfamilylaw.co.nz',
        rating: 4.8,
        reviews: 89,
        verified: true,
        featured: false,
        description: 'Compassionate family lawyers in Hamilton. Relationship property, custody, care of children, and domestic violence matters. Legal aid available. Culturally sensitive practice.',
        services: ['Relationship Property', 'Custody', 'Care of Children', 'Protection Orders', 'Mediation'],
    },
    {
        id: 38,
        name: 'Snapshot Studios',
        type: 'agency',
        category: 'photography',
        region: 'auckland',
        city: 'Ponsonby',
        phone: '09 345 6780',
        email: 'book@snapshotstudios.co.nz',
        website: 'snapshotstudios.co.nz',
        rating: 4.7,
        reviews: 112,
        verified: true,
        featured: false,
        description: 'Full-service photography and videography studio in Ponsonby. Product photography, headshots, brand content, and video production. Studio hire also available.',
        services: ['Product Photography', 'Headshots', 'Brand Content', 'Video Production', 'Studio Hire'],
    },
    {
        id: 39,
        name: 'EcoPest Welly',
        type: 'independent',
        category: 'pest-control',
        region: 'wellington',
        city: 'Petone',
        phone: '027 012 3456',
        email: 'help@ecopestwelly.co.nz',
        website: 'ecopestwelly.co.nz',
        rating: 4.6,
        reviews: 56,
        verified: true,
        featured: false,
        description: 'Eco-friendly pest control in the Wellington region. Using non-toxic, sustainable methods wherever possible. Rodents, insects, and bird proofing. Safe for pets and children.',
        services: ['Eco Pest Control', 'Rodent Control', 'Insect Treatment', 'Bird Proofing', 'Pre-Purchase Checks'],
    },
    {
        id: 40,
        name: 'All Blacks Moving Co.',
        type: 'agency',
        category: 'moving',
        region: 'auckland',
        city: 'Penrose',
        phone: '09 678 9012',
        email: 'move@allblacksmoving.co.nz',
        website: 'allblacksmoving.co.nz',
        rating: 4.7,
        reviews: 234,
        verified: true,
        featured: true,
        description: 'Auckland\'s most trusted moving company. Local moves, nationwide relocations, and international shipping. Professional packing, careful handling, and competitive rates.',
        services: ['Local Moves', 'Nationwide', 'International', 'Packing Service', 'Storage', 'Commercial Moves'],
    },
];
